#!/bin/sh
# Regenerates tests/TEST_COUNTS.md, or checks the committed copy against reality.
#
# WHY A TABLE AND NOT A NUMBER. This repo used to carry a running total in eight
# places across four files. Nothing read them, every added test invalidated all
# eight, and they went stale for four commits at a time - inside the very
# paragraphs warning that "100% tests passed out of N" is a misleading headline.
# One generated table replaces all of it, and the total stops being something a
# human maintains.
#
# WHY PER SUITE. A total only moves. A per-suite table says WHICH way and WHERE,
# and that is the difference between a report and a regression check: a suite
# that loses cases is a deletion, a suite that vanishes is a file that stopped
# compiling into the binary or a fixture that stopped being found. Neither shows
# up in a total that someone also added tests to.
#
#   tests/test_counts.sh --write    regenerate tests/TEST_COUNTS.md
#   tests/test_counts.sh --check    compare committed vs actual; non-zero on drift
#
# --check is what CI and the pre-commit habit want. It prints a suite-by-suite
# diff and separates the two cases that matter:
#
#   REGRESSION  a suite lost cases, or disappeared entirely
#   GROWTH      a suite gained cases, or a new suite appeared
#
# Growth is normal and is not an error on its own - it means the table needs
# regenerating. A regression is never automatically fine.
#
# NOTE ON WHAT THIS COUNTS: registered cases, not executed ones. A test that
# GTEST_SKIPs still registers, which is exactly why the CI column exists - see
# "Skipped is not passed" in CLAUDE.md. The executed figure is the total minus
# the suites marked as not running in CI.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
BUILD=${NES_BUILD_DIR:-$ROOT/build}
TABLE="$ROOT/tests/TEST_COUNTS.md"

# Suites CI cannot run, and why. The SingleStepTests vectors are 1.1 GB that CI
# does not fetch; commercialRom needs a cartridge dump the user supplies. Both
# register and then skip, so they inflate any "tests passed" figure.
#
# DELIBERATELY UNANCHORED. gtest names a parameterised suite
# `Prefix/Suite.case/param`, so these arrive as `AllOpcodes/SingleStepBusTrace`.
# The first draft of this script anchored with ^, matched nothing, and reported
# 902 executed in CI instead of 390 - a pattern that cannot match is
# indistinguishable from one that found nothing wrong, which is the failure this
# whole file exists to make visible. Any change here must be checked against a
# known figure, not eyeballed.
CI_SKIPPED_PATTERN='(SingleStepBusTrace|SingleStepVectors|commercialRom)'

if [ ! -x "$BUILD/tests/tests" ]; then
    echo "no test binary at $BUILD/tests/tests - build first, or set NES_BUILD_DIR" >&2
    exit 2
fi

generate() {
    # ctest -N lists without running. Test names are `Suite.case`, or
    # `Prefix/Suite.case/param` for parameterised ones; the suite key is
    # everything before the first dot, which keeps each INSTANTIATE_TEST_SUITE_P
    # group together rather than splitting it per parameter.
    listing=$(ctest --test-dir "$BUILD" -N 2>/dev/null | sed -n 's/^ *Test *#[0-9]*: //p')

    total=$(echo "$listing" | grep -c . || true)
    skipped=$(echo "$listing" | grep -cE "$CI_SKIPPED_PATTERN" || true)
    executed=$((total - skipped))

    echo "<!-- GENERATED by tests/test_counts.sh --write. Do not edit by hand. -->"
    echo "# Test counts"
    echo
    echo "Registered cases per suite. Regenerate with \`tests/test_counts.sh --write\`;"
    echo "check for regressions with \`tests/test_counts.sh --check\`."
    echo
    echo "\`ctest\` counts a skipped test as a pass, so the figure that means anything is"
    echo "**executed**. The CI column is what makes the difference visible."
    echo
    echo "| Suite | Cases | Runs in CI |"
    echo "|---|---:|---|"

    echo "$listing" | sed 's/\..*//' | sort | uniq -c | sort -k2 | while read -r count suite; do
        if echo "$suite" | grep -qE "$CI_SKIPPED_PATTERN"; then
            ci="no"
        else
            ci="yes"
        fi
        printf '| `%s` | %s | %s |\n' "$suite" "$count" "$ci"
    done

    echo
    echo "| | Cases |"
    echo "|---|---:|"
    printf '| Registered | %s |\n' "$total"
    printf '| Skipped in CI | %s |\n' "$skipped"
    printf '| **Executed in CI** | **%s** |\n' "$executed"
    echo
    echo "Skipped in CI: the 512 per-opcode SingleStepTests need 1.1 GB of vectors CI"
    echo "does not fetch, and \`commercialRom\` needs a cartridge dump nothing here will"
    echo "ever download. Locally, with both present, every registered case executes."
}

case "${1:---check}" in
--write)
    generate >"$TABLE"
    echo "wrote $TABLE"
    ;;

--check)
    if [ ! -f "$TABLE" ]; then
        echo "$TABLE does not exist - run: tests/test_counts.sh --write" >&2
        exit 2
    fi

    actual=$(generate)
    if [ "$actual" = "$(cat "$TABLE")" ]; then
        echo "test counts match $TABLE"
        exit 0
    fi

    # Compare suite by suite rather than diffing the rendered table, so the
    # output names the suite and the direction instead of showing markdown.
    old=$(grep -oE '^\| `[^`]+` \| [0-9]+' "$TABLE" | tr -d '`|' | awk '{print $1, $2}' | sort)
    new=$(echo "$actual" | grep -oE '^\| `[^`]+` \| [0-9]+' | tr -d '`|' | awk '{print $1, $2}' | sort)

    status=0
    echo "test counts differ from $TABLE:"

    # join on suite name; report each direction separately.
    for suite in $(printf '%s\n%s\n' "$old" "$new" | awk '{print $1}' | sort -u); do
        was=$(echo "$old" | awk -v s="$suite" '$1 == s {print $2}')
        now=$(echo "$new" | awk -v s="$suite" '$1 == s {print $2}')

        if [ -z "$now" ]; then
            echo "  REGRESSION  $suite: $was cases -> SUITE GONE"
            status=1
        elif [ -z "$was" ]; then
            echo "  GROWTH      $suite: new suite, $now cases"
        elif [ "$now" -lt "$was" ]; then
            echo "  REGRESSION  $suite: $was -> $now"
            status=1
        elif [ "$now" -gt "$was" ]; then
            echo "  GROWTH      $suite: $was -> $now"
        fi
    done

    if [ "$status" -ne 0 ]; then
        echo
        echo "A suite losing cases is never automatically fine: a deleted test, a file that"
        echo "stopped compiling into the binary, or a fixture that stopped being found all"
        echo "look like this. Explain it before regenerating the table." >&2
    else
        echo
        echo "Growth only. Regenerate with: tests/test_counts.sh --write"
    fi
    exit "$status"
    ;;

*)
    echo "usage: tests/test_counts.sh [--write|--check]" >&2
    exit 2
    ;;
esac
