name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Do not update man-db
      run: rm /var/lib/man-db/auto-update

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: Get latest CMake
      uses: lukka/get-cmake@latest
    
    #- name: Install ninja-build tool
    #  uses: seanmiddleditch/gha-setup-ninja@v1
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.0
    
    - name: run-cmake
      uses: lukka/run-cmake@v10.8
      #with:
        #cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        #cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        #buildDirectory: '${{ runner.workspace }}/build'
        #cmakeAppendedArgs: '-GNinja '

    - name: Build tests
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build .
    
    - name: Run tests
      working-directory: ${{ runner.workspace }}/build
      #run: ninja test
      run: make test
      
    
